# https://github.com/AmazingRise/hugo-theme-diary/blob/main/exampleSite/config.toml
baseURL = "https://markruler.github.io/"
DefaultContentLanguage = "ko"
# DefaultContentLanguage = "en"
languageCode = "ko-kr"
title = "임창수 블로그" # will set 'og:site_name'
copyright = "Im Changsu 2020 - 2024"
enableRobotsTXT = true
theme = "hugo-theme-diary"
# googleAnalytics = "60VmMXH5SqMxrPFmaJ27RuE-pn2Yg7hw1BtEkXLmOwc"

[author]
name = "Im Changsu"
email = "imcxsu@gmail.com"

# https://gohugo.io/content-management/taxonomies/
# term = "value"
[taxonomies]
tag = "tags"
category = "categories"
series = "series"
# If you do not want Hugo to create any taxonomies, set disableKinds in your site config to the following:
# disableKinds = ["taxonomy", "term"]

[markup]
  defaultMarkdownHandler = "goldmark"
  # defaultMarkdownHandler = "blackFriday"
[markup.tableOfContents]
  ordered = false
  startLevel = 2
  endLevel = 4
[markup.goldmark]
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
    autoHeadingIDType = "github"
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false
    xhtml = false
[markup.blackFriday]
  hrefTargetBlank = false
[markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_lines = 0
  lineNos = false
  anchorLineNos = false
  lineAnchors = 1
  lineNoStart = 1
  lineNumbersInTable = false
  noClasses = true
  # https://xyproto.github.io/splash/docs/longer/all.html
  # style = "api"
  style = "dracula" # 메서드명이 초록색이라서 기능을 빨리 파악할 수 있고, 주석과 뚜렷하게 구별되는 코드 색상 
  # style = "fruity"
  # style = "monokai"
  # style = "native"
  # style = "paraiso-dark"
  # style = "rrt"
  # style = "solarized-dark"
  # style = "solarized-dark256"
  # style = "vim"
  tabWidth = 2

[params]
subtitle = "What, Why, How."
favicon = "/images/favicon.ico"
# comment
enableGitalk = false
enableGiscus = false
# TOC
enableTocAutoCollapse = false
# Twitter Card and Open Graph settings
description = "임창수 기술 블로그"  # will set 'og:description'
enableOpenGraph = true
enableTwitterCards = true
images = ["/images/master/markruler-wave.webp"]
enableAutoDarkMode = true

[params.gitalk]
owner = "markruler"
repo = "markruler.github.io"
client_id = ""
client_secret = ""

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
data_repo="username/repo"
data_repo_id="**************************"    
data_category="General"
data_category_id="*********************"
data_mapping="pathname"
data_strict="0"
data_reactions_enabled="1"
data_emit_metadata="0"
data_input_position="bottom"
data_theme="preferred_color_scheme"
data_lang="en"
crossorigin="anonymous"


[[menu.main]]
url = "/about"
name = "About"
weight = 1
[[menu.main]]
url = "/posts"
name = "Posts"
weight = 2
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 4
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 10
